[tool.poetry]
name = "mimicpy"
version = "0.1.0"
description = ""
authors = ["Frolov Daniil <byka72@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
keyboard = "^0.13.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
